[global_parameters]
n_j = 15                           # Number of jobs
n_m = 15                           # Number of machines
low = 1                            # Minimum processing time
high = 99                          # Maximum processing time
instance_type = "unweighted"   # Options: "unweighted", "uniform", "differentiated"
seed = 2024                        # Random seed for reproducibility
device = "cpu"                     # Device for execution
n_instances = 5                    # Number of instances to generate

[output_parameters]
save_results = true
save_gantt = false
show_gantt = false
show_precedences = false             
base_dir = "./results/performance_analysis"
experiment_name = "experiment_3"
folder_name = "./results/experiment"      

# Parameters specific to L2D configuration
[l2d_specific]
trained_policy = "/saved_models/15_15_1_99.pth"
sample = false
is_weighted = false

# Parameters specific to dispatching rules configuration
[dispatching_specific]
logbook = false
machine_assignment_rule = "SPT"    # For SPT dispatching rule